name: Deploy EKS Cluster

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform for EKS Cluster
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Initialize Terraform
      run: terraform init

    - name: Format Terraform
      run: terraform fmt --recursive

    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply for EKS Cluster
      run: terraform apply -auto-approve tfplan


