name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm destruction'
        required: true

jobs:
  terraform-destroy:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Destroy
      run: |
        terraform plan -destroy -out=tfplan
        terraform show -json tfplan > destroy_plan.json

    - name: Apply Terraform Destroy
      run: terraform apply -auto-approve tfplan
